# Generated by Django 2.2.5 on 2019-09-24 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='FarmProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('type_doc', models.CharField(choices=[('cnpj', 'CNPJ'), ('cpf', 'CPF')], max_length=45)),
                ('num_doc', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Pavilion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PersonGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45)),
                ('addressIP', models.CharField(max_length=45, null=True)),
                ('controlBoard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.ControlBoard')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Data da leitura')),
                ('value', models.FloatField()),
                ('row', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Row')),
                ('sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Sensor')),
                ('variable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Variable')),
            ],
        ),
        migrations.AddField(
            model_name='row',
            name='sensors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Sensor'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45, null=True)),
                ('phone', models.CharField(max_length=45)),
                ('type_doc', models.CharField(choices=[('cnpj', 'CNPJ'), ('cpf', 'CPF')], max_length=45)),
                ('num_doc', models.CharField(max_length=45)),
                ('farmProperty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.FarmProperty')),
                ('personGroup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.PersonGroup')),
            ],
        ),
        migrations.AddField(
            model_name='controlboard',
            name='pavilion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Pavilion'),
        ),
    ]
