# Generated by Django 2.2.5 on 2019-09-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row',
            name='sensors',
        ),
    ]
