# Generated by Django 2.2.5 on 2019-09-25 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_row_sensors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='controlBoard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.ControlBoard'),
        ),
    ]
