# Generated by Django 2.2.5 on 2019-09-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190925_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='variable',
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da leitura'),
        ),
        migrations.DeleteModel(
            name='Variable',
        ),
    ]
