# Generated by Django 2.2.5 on 2019-09-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190926_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='nick',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
