# Generated by Django 2.2.5 on 2019-09-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_row_nick'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlboard',
            name='nick',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='pavilion',
            name='nick',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='nick',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
