# Generated by Django 2.2.6 on 2019-10-06 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190929_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='farmProperty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FarmProperty'),
        ),
        migrations.AlterField(
            model_name='person',
            name='personGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PersonGroup'),
        ),
    ]
