# Generated by Django 2.2.6 on 2019-10-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191006_1124'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='persongroup',
            table='pgroup',
        ),
    ]
