# Generated by Django 2.2.6 on 2019-10-06 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191006_1139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonGroup',
            new_name='Person_Group',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='farmProperty',
            new_name='farm',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='personGroup',
            new_name='group',
        ),
        migrations.AlterModelTable(
            name='person_group',
            table=None,
        ),
    ]
