# Generated by Django 2.2.6 on 2019-10-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ajustnewtemp',
            name='user',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='AjustNewTemp',
        ),
    ]
