# Generated by Django 2.2.6 on 2019-10-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_ajusttempnew_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajusttempnew',
            name='row',
            field=models.IntegerField(),
        ),
    ]
