# Generated by Django 2.2.6 on 2019-10-08 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20191008_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajusttempnew',
            name='row',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Row'),
        ),
    ]
