# Generated by Django 2.2.6 on 2019-10-08 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0023_auto_20191008_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjustStatusNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data do registro')),
                ('row', models.IntegerField(null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Ligada'), (0, 'Desligada')])),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
