# Generated by Django 2.2.5 on 2019-10-11 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_ajuststatusnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='row',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Row'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Sensor'),
        ),
    ]
