# Generated by Django 2.2.5 on 2019-10-12 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20191011_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajuststatusnew',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ajusttempnew',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='row',
            name='controlBoard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ControlBoard'),
        ),
    ]
