# Generated by Django 2.2.5 on 2019-10-16 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20191012_0651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='date',
            new_name='read_date',
        ),
    ]
