# Generated by Django 2.2.5 on 2019-10-28 10:54

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20191016_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajuststatusnew',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ligar'), (0, 'Desligar')]),
        ),
        migrations.AlterField(
            model_name='ajusttempnew',
            name='value',
            field=models.FloatField(validators=[app.validators.validate_value_ajust_temp]),
        ),
    ]
