# Generated by Django 2.2.5 on 2019-10-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20191028_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row',
            name='addressIP',
        ),
        migrations.AddField(
            model_name='row',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ativa'), (0, 'Inativa')], default=0),
        ),
    ]
