# Generated by Django 2.2.5 on 2019-11-05 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20191031_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='RowConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progtemp', models.FloatField()),
                ('row', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Row')),
            ],
        ),
    ]
