# Generated by Django 2.2.5 on 2019-11-06 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_rowconf'),
    ]

    operations = [
        migrations.CreateModel(
            name='RowDefaultConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progtemp', models.FloatField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Ligada'), (0, 'Desligada')])),
                ('row', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Row')),
            ],
        ),
        migrations.DeleteModel(
            name='RowConf',
        ),
    ]
