# Generated by Django 2.2.5 on 2019-11-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20191105_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowdefaultconf',
            name='envtemp',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rowdefaultconf',
            name='temp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rowdefaultconf',
            name='progtemp',
            field=models.FloatField(null=True),
        ),
    ]
